// Generated by CoffeeScript 1.6.3
var archiveFtpAddress, archiveFullPath, archiveName, fs, now, path, sh, source, target;

sh = require('execSync');

fs = require('fs');

path = require('path');

source = "X:\\srmuxroot\\STE9000\\SYSTEM\\ACTIVITY";

if (!fs.existsSync(source)) {
  console.log("" + source + " doesn't exist. Stopped.");
  console.log("You may need to map \\\\hpujcsc3.jpn.agilent.com\\srmuxroot to X: first.");
  return;
}

now = new Date();

archiveName = "ACTIVITY.hpujcsc3." + (now.getFullYear()) + (now.getMonth() + 1) + (now.getDate()) + (now.getHours()) + (now.getMinutes()) + (now.getSeconds());

archiveFullPath = source.replace("ACTIVITY", archiveName);

console.log("Archiving " + source + " to " + archiveFullPath + " ...");

sh.exec("copy /Y /V " + source + " " + archiveFullPath);

archiveFtpAddress = "\\\\ste.chn.agilent.com\\D$\\STE_Activity_Log_FTP";

target = path.join(archiveFtpAddress, archiveName);

console.log("Copying " + archiveFullPath + " to " + target + " ...");

sh.exec("copy /Y /V " + archiveFullPath + " " + target);

console.log("Deleting " + source + " ...");

if (fs.existsSync(target) || fs.existsSync(archiveFullPath)) {
  sh.exec("del /F /Q " + source + " /y");
}
