// Generated by CoffeeScript 1.6.3
(function() {
  var fs, util, utility;

  fs = require('fs');

  util = require('util');

  utility = (function() {
    function utility() {}

    utility.prototype.lastModifiedTime = function(file) {
      var info;
      info = util.inspect(fs.stat(file));
      return info.mtime;
    };

    return utility;

  })();

  module.exports = utility;

}).call(this);
