// Generated by CoffeeScript 1.6.3
var allActivities, fs, path, polarbearFtp, sh, steFtp;

polarbearFtp = "\\\\polarbear.chn.agilent.com\\H$\\Data\\ActivityLog";

steFtp = "\\\\ste.chn.agilent.com\\D$\\STE_Activity_Log_FTP";

fs = require('fs');

sh = require('execSync');

path = require('path');

if (!fs.existsSync(polarbearFtp)) {
  console.log("Can't access " + polarbearFtp + ". Stopped.");
  console.log("Make sure you have administrator permission on this shared drive.");
  return;
}

if (!fs.existsSync(steFtp)) {
  console.log("Can't access " + steFtp + ". Stopped.");
  console.log("Make sure you have administrator permission on this shared drive.");
  return;
}

allActivities = fs.readdirSync(polarbearFtp);

allActivities.forEach(function(activity) {
  var archiveActivity, archiveFolder, itemFullPath, lastModifiedTime, stat, target;
  itemFullPath = path.join(polarbearFtp, activity);
  stat = fs.statSync(itemFullPath);
  if (stat.isFile()) {
    console.log("Processing " + itemFullPath + " ...");
    lastModifiedTime = stat.mtime;
    archiveFolder = path.join(polarbearFtp, "" + (lastModifiedTime.getFullYear()) + "." + (lastModifiedTime.getMonth()) + "." + (lastModifiedTime.getDate()));
    if (!fs.existsSync(archiveFolder)) {
      console.log("Creating archive folder: " + archiveFolder + " ...");
      fs.mkdirSync(archiveFolder);
    }
    archiveActivity = path.join(archiveFolder, activity);
    console.log("Archiving " + activity + " to " + archiveActivity + " ...");
    sh.exec("move /Y " + itemFullPath + " " + archiveFolder);
    if (!fs.existsSync(archiveActivity)) {
      return console.log("Archive " + activity + " has exception.");
    } else {
      target = path.join(steFtp, activity);
      sh.exec("copy /Y /V " + archiveActivity + " " + target);
      if (fs.existsSync(target)) {
        return console.log("Copied " + activity + " to " + target + " successfully!");
      }
    }
  }
});
