// Generated by CoffeeScript 1.6.3
var configureFile, fs, sh;

fs = require('fs');

sh = require('execSync');

configureFile = "./scheduleTasks.txt";

fs.readFile(configureFile, function(err, data) {
  return String(data).split('\r\n').forEach(function(line) {
    if (line.trim() !== "") {
      console.log("Running coffee " + line + " ...");
      return sh.exec("coffee " + line);
    }
  });
});
