// Generated by CoffeeScript 1.6.3
var Person;

Person = (function() {
  function Person(name) {
    this.name = name;
    ({
      talk: function() {
        return console.log("my name is " + this.name);
      }
    });
  }

  Person.prototype.sayName = function() {
    return "my name is " + this.name;
  };

  return Person;

})();

module.exports = Person;
