// Generated by CoffeeScript 1.6.3
(function() {
  var subversion;

  subversion = (function() {
    function subversion() {}

    subversion.prototype.hasChange = function(folder) {
      return true;
    };

    subversion.prototype.update = function(folder) {};

    return subversion;

  })();

  module.exports = subversion;

}).call(this);
