// Generated by CoffeeScript 1.6.3
(function() {
  var command, createPackageExe, defaultCustomizedFileRootDir, fs, hqCommonFileRootDir, outputInstallMsi, path, releaseFolder, result, sh, tempRootDir, xcopy;

  xcopy = "C:\\Windows\\System32\\xcopy.exe";

  createPackageExe = "C:\\WCSS\\Ste\\STE_WN_SERVER\\PROJECTS\\DeveloperToolSet\\CreateStePackage\\PackageCreator.Console\\bin\\Debug\\CreatePackage.exe";

  releaseFolder = "\\\\ste.chn.agilent.com\\ste_packages\\SecuredStePackages";

  hqCommonFileRootDir = "\\\\ste.chn.agilent.com\\HQ_DIST_SERVER";

  defaultCustomizedFileRootDir = "C:\\WCSS\\Ste\\STE_Default_Customized_Files\\srmuxroot";

  tempRootDir = "C:\\srmuxroot_secure";

  outputInstallMsi = "C:\\temp\\SteInstaller.msi";

  fs = require('fs');

  sh = require('execSync');

  path = require('path');

  console.log("Copying default customized files ...");

  command = "" + xcopy + " " + defaultCustomizedFileRootDir + "\\*.* " + tempRootDir + " /E /Y /R /C /F /V";

  console.log(command);

  result = sh.exec(command);

  console.log(result.stdout);

  console.log(result);

}).call(this);
