// Generated by CoffeeScript 1.6.3
var TmePackageBuilder;

TmePackageBuilder = (function() {
  function TmePackageBuilder() {}

  TmePackageBuilder.devenvCommand = "";

  TmePackageBuilder.prototype.useDevenvVersion = function(version) {
    return this.devenvCommand = "C:\\Program Files (x86)\\Microsoft Visual Studio " + version + "\\Common7\\IDE\\devenv.com";
  };

  TmePackageBuilder.prototype.updateSourceCode = function() {};

  TmePackageBuilder.prototype.buildSolution = function(solution) {};

  TmePackageBuilder.prototype.cleanSolution = function(solution) {};

  return TmePackageBuilder;

})();

module.exports = TmePackageBuilder;
